### ISSUE TITLE
Navbar hides the content on all page

### ISSUE THREAD

**Issue by bencelaszlo** [stchristian/mealteam#2]
Navbar hides the content on all pages, definitely. This problem is not visible on index page, because the jumbotron is nested by a container, but the navbar hides the container if you check it. On other pages, the problem is more visible, it nearly hides the main title.

I was trying to add such CSS rules as margin-top to content containers or margin-bottom to navbar, but none of which worked.

**Comment by bencevarga666** [comment]
The problem is solved by @stchristian with his improved navbar.
