### ISSUE TITLE
Contact infó a kezdőoldalon

### ISSUE THREAD

**Issue by stchristian** [stchristian/mealteam#5]
Szerintem felesleges hogy a contact page, lehetne a kezdőoldalon legalul, úgy hogy a kapcsolat link odamutat.

**Comment by bencevarga666** [comment]
Továbbmegyek: ez oda fog kilyukadni, hogy a content-heavy galérián kívül minden mehet a kezdőlapra, a szabályzat pedig a hosszabb szövege miatt egy gombbal legyen lenyitható.

**Comment by bencevarga666** [comment]
index.html, contact.html, rules.html egyesítve.

index.html, contact.html, rules.html are merged now.
